### ISSUE TITLE
Errors in using the code

### ISSUE THREAD

**Issue by ASDumon** [patonlab/Kinisot#1]
Hello,

I am encountering issues when trying this package.

Upon trying python Kinisot.py Reactant.log TS.log -iso "3" -s 1.0 I get an error (TypeError: list indices must be integers or slices, not float   ligne 61 from Hess_to_Freq.py)

I am using Anaconda on MacOS.

I am at loss on what to do to solve that.

Best regards.

**Comment by bobbypaton** [comment]
Should now be fixed, sorry about that. 

The code was recently updated from python 2 to 3, however, there were two integer division operators that had not been converted properly. 

I can now reproduce the example results again.

**Comment by ASDumon** [comment]
Thanks for that but it is still not working for me. 

I get a RuntimeWarning: invalid value encountered in double_scalars on the EXC and TRPF.

I fixed some errors in the Hess_to_freq.py file (that arise from going from python 2.0 to 3.0), but this error arise from a division by 0 but I cannot find where the error is.

I used a scalar factor of 0.0 because if the value is different from 0, I get  RuntimeWarning: invalid value encountered in log on line 95 in Kinisot.py that I cannot fix either.

**Comment by bobbypaton** [comment]
Thanks for the follow-up.

Can you not run the example files? (python Kinisot.py Cl_H_Cl_RCT.out Cl_H_Cl_TS.out -iso "1"). This seems to be working fine with the current version for me. If not, please could you paste the full error from python?

The scale factor for all methods should be close to 1. A value of zero will be unphysical.

**Comment by ASDumon** [comment]
How can I find the files?

**Comment by bobbypaton** [comment]
https://github.com/bobbypaton/Kinisot/tree/master/kinisot/examples

**Comment by ASDumon** [comment]
I get this.

Wrong number of arguments used. Correct format: Kinisot.py 2 x g09_output_files -iso 1 2 3 (-t <temp>) (-s <scalefactor>) (-cutoff <value>)

WIth python Kinisot.py Cl_H_Cl_RCT.out Cl_H_Cl_TS.out -iso "1"

**Comment by bobbypaton** [comment]
For the above command to work, the files need to be in the same directory as the python script. Here's the complete workflow that should work:

git clone https://github.com/bobbypaton/Kinisot.git
cd Kinisot/kinisot

python Kinisot.py examples/Cl_H_Cl_RCT.out examples/Cl_H_Cl_TS.out -iso "1" -s 1

**Comment by ASDumon** [comment]
It works! Thanks a lot!

I will try to find out why when I installed using pip install the version was not the same as the one using git clone.
